### PR TITLE
Clustering support

### LINKED ISSUE #66: Clustering
Hi,
I need support for Quartz clustering - i.e., N > 1 servers, a repeating job runs exactly on one server for every repetition, possibly on a different server each time - using MongoDB as the datastore.

Are you working on adding support for clustering? Are there any technical issues that make the implementation difficult, or it's just a matter of having the time to write the code?

Thanks!

### PR DESCRIPTION
**Pull request by pwojnowski**
Most commits just refactor code to smaller, understandable and testable, parts.

The most important changes are around acquiring triggers and LocksDao.

Fixes #66

### CODE REVIEW

**Comment by nikos** [comment]
Thanks a lot @pwojnowski for working and sharing your clustering improvements, hopefully they will be part of Michael's master branch soon :-)

**Comment by msimerson** [comment]
Nice work. Thanks @pwojnowski. I was looking at opening a PR to update to mongo 3.2 driver, but I'd like to see this land first.

**Comment by connollyst** [comment]
Would love to see this branch merged. Any way I can help?

**Comment by michaelklishin** [comment]
@connollyst there are merge conflicts with master. The need to be resolved.

**Comment by pwojnowski** [comment]
@michaelklishin I already incorporated the commits from other PR and everything builds fine. I don't know why GH shows that my branch has conflicts.

I'm still working on Failover, because it doesn't work for all possible cases. But if this should ever be merged then IMHO it would be better do so now to allow other people to contribute without creating conflicting PRs all the time - at this momemnt it is inevitable, because the code structure has changed a lot.

Another thing is IMHO it would be better to change tests from Clojure to something where creating mocks is much simpler (e.g. Spock Framewok). I like Clojure, but writing Clojure tests for Java code is often painful and TDD is basically impossible.
I can rewrite tests to Spock if you agree to do so.

**Comment by pwojnowski** [comment]
ok, I've corrected failover part. Now nodes can recover own and other nodes' triggers.

I'm not sure about two things:
1. Currently, when a node cannot check-in on time it shuts down the JVM, but it would be better to just close Quartz Scheduler. It would be best to turn QS into standby mode, but it's not implemented.
2. IMHO WriteConcern should not be JOURNALED, because it doesn't wait for replicas to get wrote data. It would be better to set something like MAJORITY+JOURNALED.

**Comment by michaelklishin** [comment]
@pwojnowski I am perfectly fine with switching to `MAJORITY+JOURNALED`. As for stand by mode, if you feel it's worth using, then please implement support for it and lets use that.

I am interested in merging this. Thank you for your time.

**Comment by michaelklishin** [comment]
@pwojnowski let me know when this is ready for one last review and merging. Thank you.

**Comment by pwojnowski** [comment]
@michaelklishin now it is ready to be merged. Today I just added docs and removed one deprecation.

In case of other changes I will create another PR - for example to other issues.

**Comment by michaelklishin** [comment]
@pwojnowski thank you! Please update [change log](https://github.com/michaelklishin/quartz-mongodb/blob/master/ChangeLog.md) and credit yourself. It'd be great to have this documented well :)

**Pull request merged**
