### PR TITLE
Scheduler cannot remove own expired lock

### PR DESCRIPTION
**Pull request by arulrajnet**
- Change the isTriggerLockExpired to as like isJobLockExpired

Schedular | Trigger Timeout | isTriggerLockExpired
-- | -- | --
ALIVE | Yes | TRUE
ALIVE | No | FALSE
DEAD | Yes | TRUE
DEAD | No | TRUE

Fix of #196

### CODE REVIEW

**Comment by michaelklishin** [comment]
The "OR" condition makes more sense, thanks.

**Comment by michaelklishin** [comment]
@arulrajnet if you are interested, I would be happy to add you as a collaborator for this repo. WDYT?

**Comment by arulrajnet** [comment]
@michaelklishin Yes I am interested.

**Comment by michaelklishin** [comment]
@arulrajnet invite sent!

**Pull request merged**
