### PR TITLE
Make Job Data serialization to base64 optional.

### PR DESCRIPTION
**Pull request by dorogush**
Storing Job Data as a `base64` should be optional (but default). Other option is to store directly as embedded document (if only simple types are used).

### CODE REVIEW

**Comment by dorogush** [comment]
@michaelklishin @pwojnowski please review.

**Comment by michaelklishin** [comment]
Please add some test cases.

**Comment by dorogush** [comment]
Done

**Comment by pwojnowski** [comment]
To me it looks ok.

**Comment by pwojnowski** [comment]
Thank you! :+1:

**Comment by dorogush** [comment]
Is it possible to publish to public repo?
I plan to use it in production and I need this and #103

**Comment by michaelklishin** [comment]
@dorogush we will do our best to release another preview of 2.0 this week.

**Comment by dorogush** [comment]
@michaelklishin thanks!

**Comment by dorogush** [comment]
@michaelklishin Any update on release?

**Comment by michaelklishin** [comment]
I tried publishing to oss.sonatype.org only to be reminded that it's such a shit show. I need to wait for a JIRA ticket to be resolved before can do that and then hope my reading of the docs for Nexus deployment was correct.

**Comment by michaelklishin** [comment]
Alternatively I can investigate releasing to Bintray. We will see which way ends up being more straightforward. Ultimately both can promote to Maven Central.

**Comment by michaelklishin** [comment]
@dorogush can you please give https://bintray.com/michaelklishin/maven/quartz-mongodb/2.0.0-rc3 a try?

**Comment by dorogush** [comment]
Maven Central is indeed a bit harder to bootstrap. You need to configure your build tool to also generate javadoc and source jars, artifacts should be signed with gnupg. Also, if you want to fully automate the process, you need to configure nexus plugin for the build tool, so the artifact will be automatically promoted from sonatype repo to maven central.
Anyway, I'm glad you you published to bintray. Artifact is now available:
```
<repositories>
    <repository>
        <id>michaelklishin</id>
        <url>https://dl.bintray.com/michaelklishin/maven/</url>
    </repository>
</repositories>
```
```
<dependency>
    <groupId>com.novemberain</groupId>
    <artifactId>quartz-mongodb</artifactId>
    <version>2.0.0-rc3</version>
</dependency>
```
In addition i believe you can easily promote your artifacts to jcenter, so the url will be
`http://jcenter.bintray.com/`

**Pull request merged**
